name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Prepare deployment
        run: |
          # Create test index.html
          echo "<!DOCTYPE html><html><head><title>Test Page</title></head><body><h1>Test Page</h1><p>If you see this, GitHub Pages is working.</p></body></html>" > dist/test.html
          
          # Debug: Show initial build output
          echo "Initial build output:"
          ls -la dist/
          
          # Create rc-friends-cricket-league directory
          mkdir -p dist/rc-friends-cricket-league
          
          # Move all build files to rc-friends-cricket-league directory
          mv dist/* dist/rc-friends-cricket-league/ 2>/dev/null || true
          mv dist/rc-friends-cricket-league/test.html dist/index.html
          
          # Create 404.html
          cp dist/rc-friends-cricket-league/index.html dist/rc-friends-cricket-league/404.html
          
          # Debug: Show final directory structure
          echo "Final directory structure:"
          ls -R dist/
          
          # Show contents of key files
          echo "Contents of dist/index.html:"
          cat dist/index.html
          echo "Contents of dist/rc-friends-cricket-league/index.html:"
          cat dist/rc-friends-cricket-league/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 